### ISSUE TITLE
Register in bower.io

### ISSUE THREAD

**Issue by ivan-zakharchuk** [seavor/vunits-sass-poly#1]
Hello, 

this is actually good poly, so would you like register it on http://bower.io/docs/creating-packages/ ? 

Thanks.

**Comment by markhughes** [comment]
I agree, this poly needs more attention!

**Comment by seavor** [comment]
@ivanzvakoms @MarkehMe 

Thank you for the interest! Been so busy with work I haven't had time to check my own stuff lol I hadn't thought about it, but i don't see why not. I'll see if I can't get around to it, it's still in development, but some extra eyes would be nice. It would definitely motivate me to finish the thing.

**Comment by seavor** [comment]
Done! Readme files to come one day, but the repo is installable via

<code>bower install vunits-sass-poly</code>
